export const GET_MOVIES = 'GET_MOVIES';
export const CREATE_MOVIES = 'CREATE_MOVIES';
export const UPDATE_MOVIES = 'UPDATE_MOVIES';
export const DELETE_MOVIES = 'DELETE_MOVIES';
export const CLEAR_MOVIES = 'CLEAR_MOVIES';